language: elixir
sudo: false
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 18.2
  - 19.1
  - 20.0
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
    - elixir: 1.5
      otp_release: 18.2
    - elixir: 1.5
      otp_release: 19.1
    - elixir: 1.6
      otp_release: 18.2
    - elixir: 1.6
      otp_release: 19.1
before_script:
  - mix deps.get --only test
script:
  - ./bin/checks.sh
